# Digital Ocean App Platform Spec
# Import this when creating the app, or use `doctl apps create --spec .do/app.yaml`

name: nostrdevs
region: nyc

services:
  - name: web
    github:
      repo: dtdannen/nostrdevs
      branch: main
      deploy_on_push: true
    build_command: npm install && node build.js
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FIRECRAWL_API_KEY
        scope: RUN_TIME
        type: SECRET
